services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'

  auth-ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=users_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - JWT_SECRET=secret
      - JWT_EXPIRATION=3600
    ports:
      - '8000:8000'
    depends_on:
      - postgres

